#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/main.css" />
* The Four Agreements
** Be Impeccable With Your Word
** Don't take anything personally
** Don't make assumptions

Making assumptions in our relationships is really asking for
problems. Often we make the assumption that our partners know what we
think and that we don’t have to say what we want. We assume they are
going to do what we want, because they know us so well. If they don’t
do what we assume they should do, we feel so hurt and say, “You should
have known.”

It is very interesting how the human mind works. We have the need to
justify everything, to explain and understand everything, in order to
feel safe. We have millions of questions that need answers because
there are so many things that the reasoning mind cannot explain. It is
not important if the answer is correct; just the answer itself makes
us feel safe. This is why we make assumptions.

We make all sorts of assumptions because we don't have the courage
to ask the questions.

We make the assumption that everyone sees life the way we do. We
assume that others think the way we think, feel the way we feel, judge
the way we judge, and abuse the way we abuse. This is the biggest
assumption that humans make. And this is why we have a fear of being
ourselves around others. Because we think everyone else will judge us,
victimize us, abuse us, and blame us as we do ourselves. So even
before others have a chance to reject us, we have already rejected
ourselves. That is the way the human mind works.

The way to keep yourself from making assumptions is to ask
questions. Make sure the communication is clear. If you don’t
understand, ask. Have the courage to ask questions until you are clear
as you can be, and even then do not assume you know all there is to
know about a given situation. Once you hear the answer, you will not
have to make assumptions because you will know the truth.  Also, find
your voice to ask for what you want. Everybody has the right to tell
you no or yes, but you always have the right to ask. Likewise,
everybody has the right to ask you, and you have the right to say yes
or no.
** Always Do Your Best

THERE IS JUST ONE MORE AGREEMENT, BUT IT’S THE one that allows the
other three to become deeply ingrained habits. The fourth agreement is
about the action of the first three: Always do your best.

Under any circumstance, always do your best, no more and no less. But
keep in mind that your best is never going to be the same from one
moment to the next. Everything is alive and changing all the time, so
your best will sometimes be high quality, and other times it will not
be as good. When you wake up refreshed and energized in the morning,
your best will be better than when you are tired at night. Your best
will be different when you are healthy as opposed to sick, or sober as
opposed to drunk. Your best will depend on whether you are feeling
wonderful and happy, or upset, angry, or jealous.

Doing your best is taking the action because you love it, not because
you're expecting a reward.

Under any circumstance, always do your best, no more and no less. But
keep in mind that your best is never going to be the same from one
moment to the next. Everything is alive and changing all the time, so
your best will sometimes be high quality, and other times it will not
be as good. When you wake up refreshed and energized in the morning,
your best will be better than when you are tired at night. Your best
will be different when you are healthy as opposed to sick, or sober as
opposed to drunk. Your best will depend on whether you are feeling
wonderful and happy, or upset, angry, or jealous.

Under any circumstance, always do your best, no more and no less. But
keep in mind that your best is never going to be the same from one
moment to the next. Everything is alive and changing all the time, so
your best will sometimes be high quality, and other times it will not
be as good. When you wake up refreshed and energized in the morning,
your best will be better than when you are tired at night. Your best
will be different when you are healthy as opposed to sick, or sober as
opposed to drunk. Your best will depend on whether you are feeling
wonderful and happy, or upset, angry, or jealous.

* The Little Book of Talent - Daniel Coyle
  
** "TIP #1 STARE AT WHO YOU WANT TO BECOME"


"If you were to visit a dozen talent hotbeds tomorrow, you would be
struck by how much time the learners spend observing top
performers. When I say “observing,” I’m not talking about passively
watching. I’m talking about staring—the kind of raw, unblinking,
intensely absorbed gazes you see in hungry cats or newborn babies."


"We each live with a “windshield” of people in front of us; one of the
keys to igniting your motivation is to fill your windshield with vivid
images of your future self, and to stare at them every day. Studies
show that even a brief connection with a role model can vastly
increase unconscious motivation. For example, being told that you
share a birthday with a mathematician can improve the amount of effort
you’re willing to put into difficult math tasks by 62 percent."


"Think of your windshield as an energy source for your brain. Use
pictures (the walls of many talent hotbeds are cluttered with photos
and posters of their stars) or, better, video. One idea: Bookmark a
few YouTube videos, and watch them before you practice, or at night
before you go to bed."


** "TIP #2 SPEND FIFTEEN MINUTES A DAY ENGRAVING THE SKILL ON YOUR BRAIN"


"What’s the best way to begin to learn a new skill? Is it by listening
to a teacher’s explanation? Reading an instructional book? Just
leaping in and trying it out? Many hotbeds use an approach I call the
engraving method."


"The key to effective engraving is to create an intense connection: to
watch and listen so closely that you can imagine the feeling of
performing the skill. For physical skills, project yourself inside the
performer’s body. Become aware of the movement, the rhythm; try to
feel the interior shape of the moves. For mental skills, simulate the
skill by re-creating the expert’s decision patterns. Chess players
achieve this by replaying classic games, move by move; public speakers
do it by regiving great speeches complete with original inflections;
musicians cover their favorite songs; some writers I know achieve this
effect by retyping passages verbatim from great works. (It sounds kind
of Zen, but it works.)"


"The key to effective engraving is to create an intense connection: to
watch and listen so closely that you can imagine the feeling of
performing the skill. For physical skills, project yourself inside the
performer’s body. Become aware of the movement, the rhythm; try to
feel the interior shape of the moves. "


** "TIP #3 STEAL WITHOUT APOLOGY"


"We are often told that talented people acquire their skill by
following their “natural instincts.” This sounds nice, but in fact it
is baloney. All improvement is about absorbing and applying new
information, and the best source of information is top performers. So
steal it."


"When you steal, focus on specifics, not general impressions. Capture
concrete facts: the angle of a golfer’s left elbow at the top of the
backswing; the curve of a surgeon’s wrist; the precise shape and
tension of a singer’s lips as he hits that high note; the exact length
of time a comedian pauses before delivering the punch line. Ask
yourself:"


"What, exactly, are the critical moves here?     • How do they perform those moves differently than I do?"


** "TIP #4 BUY A NOTEBOOK"


"A high percentage of top performers keeps some form of daily
performance journal. Tennis champion Serena Williams and former World
Series MVP Curt Schilling use notebooks;"


"What matters is that you write stuff down and reflect on it. Results
from today. Ideas for tomorrow. Goals for next week. A notebook works
like a map: It creates clarity."


** "TIP #5 BE WILLING TO BE STUPID"


"Whatever the strategy, the goal is always the same: to encourage
reaching, and to reinterpret mistakes so that they’re not verdicts,
but the information you use to navigate to the correct move."


** "TIP #6 CHOOSE SPARTAN OVER LUXURIOUS"


"Simple, humble spaces help focus attention on the deep-practice task at hand"


"reaching and repeating and struggling. When given the choice between luxurious and spartan, choose spartan. "


** "TIP #7 BEFORE YOU START, FIGURE OUT IF IT’S A HARD SKILL OR A SOFT SKILL"


"Every skill falls into one of two categories: hard skills and soft skills."


"HARD, HIGH-PRECISION SKILLS are actions that are performed as
correctly and consistently as possible, every time. They are skills
that have one path to an ideal result; skills that you could imagine
being performed by a reliable robot. Hard skills are about repeatable
precision, and tend to be found in specialized pursuits, particularly
physical ones."


"SOFT, HIGH-FLEXIBILITY SKILLS, on the other hand, are those that have
many paths to a good result, not just one. These skills aren’t about
doing the same thing perfectly every time, but rather about being
agile and interactive; about instantly recognizing patterns as they
unfold and making smart, timely choices. Soft skills tend to be found
in broader, less-specialized pursuits, especially those that involve
communication"


** "TIP #8 TO BUILD HARD SKILLS, WORK LIKE A CAREFUL CARPENTER"


"To develop reliable hard skills, you need to connect the right wires
in your brain."


"When you learn hard skills, be precise and measured. Go slowly. Make
one simple move at a time, repeating and perfecting it before you move
on. Pay attention to errors, and fix them, particularly at the start"


** "TIP #9 TO BUILD SOFT SKILLS, PLAY LIKE A SKATEBOARDER"


"While hard skills are best put together with measured precision (see
Tip #8), soft skills are built by playing and exploring inside
challenging, ever-changing environments. These are places where you
encounter different obstacles and respond to them over and over,
building the network of sensitive wiring you need to read, recognize,
and react. In other words, to build soft skills you should behave less
like a careful carpenter and more like a skateboarder in a skateboard
park: aggressive, curious, and experimental, always seeking new ways
to challenge yourself."


"When you practice a soft skill, focus on making a high number of
varied reps, and on getting clear feedback. Don’t worry too much about
making errors—the important thing is to explore. Soft skills are often
more fun to practice, but they’re also tougher because they demand
that you coach yourself. After each session ask yourself, What worked?
What didn’t? And why?"


** "TIP #10 HONOR THE HARD SKILLS"


"The point of this tip is simple: Prioritize the hard skills because
in the long run they’re more important to your talent."


"You might be surprised to learn that many top performers place great
importance on practicing the same skills they practiced as
beginners. "


"One way to keep this idea in mind is to picture your talent as a big
oak tree—a massive, thick trunk of hard skills with a towering canopy
of flexible soft skills up above. First build the trunk. Then work on
the branches"


** "TIP #11" "DON’T FALL FOR THE PRODIGY MYTH"


"If you have early success, do your best to ignore the praise and keep
pushing yourself to the edges of your ability, where improvement
happens. If you don’t have early success, don’t quit. Instead, treat
your early efforts as experiments, not as verdicts. Remember, this is
a marathon, not a sprint."


** "TIP #12 FIVE WAYS TO PICK A HIGH-QUALITY TEACHER OR COACH"


"1) Avoid Someone Who Reminds You of a Courteous Waiter"


"2) Seek Someone Who Scares You a Little"


"3) Seek Someone Who Gives Short, Clear Directions"


"4) Seek Someone Who Loves Teaching Fundamentals"


"5) Other Things Being Equal, Pick the Older Person"


"The key to deep practice is to reach. This means to stretch yourself
slightly beyond your current ability, spending time in the zone of
difficulty called the sweet spot. It means embracing the power of
repetition, so the action becomes fast and automatic. It means
creating a practice space that enables you to reach and repeat, stay
engaged, and improve your skills over time."


** "TIP #13 FIND THE SWEET SPOT"


"FIND THE SWEET SPOT There is a place, right on the edge of your
ability, where you learn best and fastest. It’s called the sweet spot"


"[Comfort Zone]"


"Sensations: Ease, effortlessness. You’re working, but not reaching or
struggling. Percentage of Successful Attempts: 80 percent and above"


"[Sweet Spot]"


"Sensations: Frustration, difficulty, alertness to errors. You’re
fully engaged in an intense struggle—as if you’re stretching with all
your might for a nearly unreachable goal, brushing it with your
fingertips, then reaching again. Percentage of Successful Attempts:
50–80 percent."


"[Survival Zone]"


"Sensations: Confusion, desperation. You’re overmatched: scrambling,
thrashing, and guessing. You guess right sometimes, but it’s mostly
luck. Percentage of Successful Attempts: Below 50 percent."


"Ask yourself: If you tried your absolute hardest, what could you
almost do? Mark the boundary of your current ability, and aim a little
beyond it. That’s your spot."


** "TIP #14" "TAKE OFF YOUR WATCH"


"Deep practice is not measured in minutes or hours, but in the number
of high-quality reaches and repetitions you make—basically, how many
new connections you form in your brain. Instead of counting minutes or
hours, count reaches and reps. "


** "TIP #15 BREAK EVERY MOVE DOWN INTO CHUNKS"


"To begin chunking, first engrave the blueprint of the skill on your
mind (see Tip #2). Then ask yourself: 1) What is the smallest single
element of this skill that I can master?  2) What other chunks link to
that chunk?"


"No matter what skill you set out to learn, the pattern is always the
same: See the whole thing. Break it down to its simplest elements. Put
it back together. Repeat."


** "TIP #16 EACH DAY, TRY TO BUILD ONE PERFECT CHUNK"


"In our busy lives, it’s sometimes tempting to regard merely
practicing as a success. We complete the appointed hour and sigh
victoriously—mission accomplished! But the real goal isn’t practice;
it’s progress. "


"One useful method is to set a daily SAP: smallest achievable
perfection. In this technique, you pick a single chunk that you can
perfect—not just improve, not just “work on,” but get 100 percent
consistently correct. "


** "TIP #17 EMBRACE STRUGGLE"


"Deep practice has a telltale emotional flavor, a feeling that can be
summed up in one word: “struggle.”"


** "TIP #18 CHOOSE FIVE MINUTES A DAY OVER AN HOUR A WEEK"


"With deep practice, small daily practice “snacks” are more effective
than once-a-week practice binges. The reason has to do with the way
our brains grow—incrementally, a little each day, even as we sleep. "


"The other advantage of practicing daily is that it becomes a
habit. The act of practicing—making time to do it, doing it well—can
be thought of as a skill in itself, perhaps the most important skill
of all. Give it time. According to research, establishing a new habit
takes about thirty days."


** "TIP #19 DON’T DO “DRILLS.” INSTEAD, PLAY SMALL, ADDICTIVE GAMES"


"Good coaches share a knack for transforming the most mundane
activities—especially the most mundane activities—into games. The
governing principle is this: If it can be counted, it can be turned
into a game. For example, playing a series of guitar chords as a drill
is boring. But if you count the number of times you do it perfectly
and give yourself a point for each perfect chord, it can become a
game. Track your progress, and see how many points you score over a
week. The following week, try to score more."


** "TIP #20 PRACTICE ALONE"


"Solo practice works because it’s the best way to 1) seek out the
sweet spot at the edge of your ability, and 2) develop discipline,
because it doesn’t depend on others. "


** "TIP #21 THINK IN IMAGES"


"Whenever possible, create a vivid image for each chunk you want to
learn. The images don’t have to be elaborate, just easy to see and
feel."


** "TIP #22 PAY ATTENTION IMMEDIATELY AFTER YOU MAKE A MISTAKE"


"Brain-scan studies reveal a vital instant, 0.25 seconds after a
mistake is made, in which people do one of two things—they look hard
at the mistake or they ignore it. People who pay deeper attention to
an error learn significantly more than those who ignore it. Develop
the habit of attending to your errors right away. Don’t wince, don’t
close your eyes; look straight at them and see what really happened,
and ask yourself what you can do next to improve. Take mistakes
seriously, but never personally."


** "TIP #23 VISUALIZE THE WIRES OF YOUR BRAIN FORMING NEW CONNECTIONS"


"When you go to the sweet spot on the edge of your ability and reach
beyond it, you are forming and strengthening new connections in your
brain. Mistakes aren’t really mistakes, then—they’re the information
you use to build the right links. The more you pay attention to
mistakes and fix them, the more of the right connections you’ll be
building inside your brain. Visualizing this process as it happens
helps you reinterpret mistakes as what they actually are: tools for
building skill"


** "TIP #24 VISUALIZE THE WIRES OF YOUR BRAIN GETTING FASTER"


"Every time you practice deeply—the wires of your brain get
faster. Over time, signal speeds increase to 200 mph from 2 mph. When
you practice, it’s useful and motivating to visualize the pathways of
your brain being transformed from simple copper wires to high-speed
broadband, because that’s what’s really happening"


** "TIP #25 SHRINK THE SPACE"


"Smaller practice spaces can deepen practice when they are used to
increase the number and intensity of the reps and clarify the goal. "


"Ask yourself: What’s the minimum space needed to make these reaches
and reps? Where is extra space hindering fast and easy communication?"


** "TIP #26 SLOW IT DOWN (EVEN SLOWER THAN YOU THINK)"


"Super-slow practice works like a magnifying glass: It lets us sense
our errors more clearly, and thus fix them. "


** "TIP #27 CLOSE YOUR EYES"


"One of the quickest ways to deepen practice is also one of the
simplest: Close your eyes. "


** "TIP #28 MIME IT"


"At talent hotbeds you will see people swinging golf clubs and tennis
rackets at empty air, playing the piano on tabletops, and skiing
imaginary slalom courses with their feet fixed on the floor. It looks
crazy, but from a deep-practice perspective it makes sense. Removing
everything except the essential action lets you focus on what matters
most: making the right reach."


** "TIP #29 WHEN YOU GET IT RIGHT, MARK THE SPOT"


"One of the most fulfilling moments of a practice session is when you
have your first perfect rep. When this happens, freeze. Rewind the
mental tape and play the move again in your mind. Memorize the
feeling, the rhythm, the physical and mental sensations. The point is
to mark this moment—this is the spot where you want to go again and
again. This is not the finish—it’s the new starting line for
perfecting the skill until it becomes automatic. As Kimberly
Meier-Sims of the Sato Center for Suzuki Studies says, “Practice
begins when you get it right.”"


** "TIP #30 TAKE A NAP"


"The science: Napping is good for the learning brain, because it helps
strengthen the connections formed during practice and prepare the
brain for the next session."


** "TIP #31" "TO LEARN A NEW MOVE, EXAGGERATE IT"


"To learn a new move, exaggerate it. If the move calls for you to lift
your knees, lift them to the ceiling. If it calls for you to press
hard on the guitar strings, press with all your might. If it calls for
you to emphasize a point while speaking in public, emphasize with
theatricality. Don’t be halfhearted. You can always dial back
later. Go too far so you can feel the outer edges of the move, and
then work on building the skill with precision."


** "TIP #32 MAKE POSITIVE REACHES"


"There’s a moment just before every rep when you are faced with a
choice: You can either focus your attention on the target (what you
want to do) or you can focus on the possible mistake (what you want to
avoid). This tip is simple: Always focus on the positive move, not the
negative one."


"For example, a golfer lining up a putt should tell herself, “Center
the stroke,” not “Don’t pull this putt to the left.” A violinist faced
with a difficult passage should tell himself, “Nail that A-flat,” not
“Oh boy, I hope I don’t miss that A-flat.” Psychologists call this
“positive framing,” and provide plentiful theories of how framing
affects our subconscious mind. The point is, it always works better to
reach for what you want to accomplish, not away from what you want to
avoid."


"Let’s pretend that one week from now you will take a test on the next
ten pages of this book. You have thirty minutes to study. Which
practice method would help you get a better grade?"


** "TIP #33 TO LEARN FROM A BOOK, CLOSE THE BOOK"


"A) Reading those ten pages four times in a row, and trying to
memorize them.  B) Reading those ten pages once, then "


"closing the book and writing a one-page summary."


"It’s not even close. Research shows that people who follow strategy B
remember 50 percent more material over the long term than people who
follow strategy A. This is because of one of deep practice’s most
fundamental rules: Learning is reaching. Passively reading a book—a
relatively effortless process, letting the words wash over you like a
warm bath—doesn’t put you in the sweet spot. Less reaching equals less
learning."


"On the other hand, closing the book and writing a summary forces you
to figure out the key points (one set of reaches), process and
organize those ideas so they make sense (more reaches), and write them
on the page (still more reaches, along with repetition). The equation
is always the same: More reaching equals more learning."


** "TIP #34 USE THE SANDWICH TECHNIQUE"


"Deep practice is about finding and fixing mistakes, so the question
naturally pops up: What’s the best way to make sure you don’t repeat
mistakes? One way is to employ the sandwich technique. It goes like
this: 1. Make the correct move.  2. Make the incorrect move.  3. Make
the correct move again. The goal is to reinforce the correct move and
to put a spotlight on the mistake, preventing it from slipping past
undetected and becoming wired into your circuitry."


** "TIP #35 USE THE 3 × 10 TECHNIQUE"


"This piece of advice comes from Dr. Douglas Fields, a neurologist at
the National Institutes of Health in Bethesda, Maryland, who
researches memory and learning. He discovered that our brains make
stronger connections when they’re stimulated three times with a rest
period of ten minutes between each stimulation. The real-world
translation: To learn something most effectively, practice it three
times, with ten-minute breaks between each rep. “I apply this to
learning all the time in my own life, and it works,” Fields says. “For
example, in mastering a difficult piece of music on the guitar, I
practice, then I do something else for ten minutes, then I practice
again [and so on].”"


** "TIP #36 INVENT DAILY TESTS"


"To invent a good test, ask yourself: What’s one key element of this
skill? How can I isolate my accuracy or reliability, and measure it?
How can I make it fun, quick, and repeatable, so I can track my
progress?"


** "TIP #37 TO CHOOSE THE BEST PRACTICE METHOD, USE THE R.E.P.S. GAUGE"


"The biggest problem in choosing a practice strategy is not that there
are too few options, but that there are too many."


"This tip provides a way to measure practice effectiveness. It’s
called the R.E.P.S. gauge. Each letter stands for a key element of
deep practice.  R: Reaching and Repeating E: Engagement P:
Purposefulness S: Strong, Speedy Feedback."


"ELEMENT 1: REACHING AND REPEATING. Does the practice have you
operating on the edge of your ability, reaching and repeating?"


"ELEMENT 2: ENGAGEMENT. Is the practice immersive? Does it command
your attention? Does it use emotion to propel you toward a goal?"


"ELEMENT 3: PURPOSEFULNESS. Does the task directly connect to the
skill you want to build?"


"ELEMENT 4: STRONG, SPEEDY FEEDBACK. Does the learner receive a stream
of accurate information about his performance—where he succeeded and
where he made mistakes?"


"The idea of this gauge is simple: When given a choice between two
practice methods, or when you’re inventing a new test or game, pick
the one that maximizes these four qualities, the one with the most
R.E.P.S."


** "TIP #38 STOP BEFORE YOU’RE EXHAUSTED"


"In many skills, particularly athletic, medical, and military ones,
there’s a long tradition of working until total exhaustion. This
tradition has its uses, particularly for improving fitness and mental
toughness, and for forging emotional connections within a group. But
when it comes to learning, the science is clear: Exhaustion is the
enemy. Fatigue slows brains. It triggers errors, lessens
concentration, and leads to shortcuts that create bad habits. It’s no
coincidence that most talent hotbeds put a premium on practicing when
people are fresh, usually in the morning, if possible. When exhaustion
creeps in, it’s time to quit."


** "TIP #39 PRACTICE IMMEDIATELY AFTER PERFORMANCE"


"The previous tip was about the importance of practicing when you’re
fresh. This tip is about a different kind of freshness, which comes in
the moment just after a performance, game, or competition. At that
moment, practicing is probably the last thing you want to do. But it’s
the first thing you should do, if you’re not too worn out, because it
helps you target your weak points and fix them. As the golfer Jack
Nicklaus said, “I always achieve my most productive practice after an
actual round. Then, the mistakes are fresh in my mind and I can go to
the practice tee and work specifically on those mistakes.”"


** "TIP #40 JUST BEFORE SLEEP, WATCH A MENTAL MOVIE"


"This is a useful habit I’ve heard about from dozens of top
performers, ranging from surgeons to athletes to comedians. Just
before falling asleep, they play a movie of their idealized
performance in their heads. A wide body of research supports this
idea, linking visualization to improved performance, motivation,
mental toughness, and confidence. Treat it as a way to rev the engine
of your unconscious mind, so it spends more time churning toward your
goals."


** "TIP #41 END ON A POSITIVE NOTE"


"A practice session should end like a good meal—with a small, sweet
reward. It could be playing a favorite game or it could be more
literal. (Chocolate works quite well.) My ten-year-old daughter ends
her violin practices with a foot-stomping rendition of the bluegrass
tune “Old Joe Clark.”"


** "TIP #42 SIX WAYS TO BE A BETTER TEACHER OR COACH"


"Sooner or later, no matter who you are, you’ll find yourself being a
teacher, a coach, or a mentor. "


"1) Use the First Few Seconds to Connect on an Emotional Level"


"2) Avoid Giving Long Speeches—Instead, Deliver Vivid Chunks of Information"


"3) Be Allergic to Mushy Language"


"4) Make a Scorecard for Learning"


"5) Maximize “Reachfulness”"


"6) Aim to Create Independent Learners"


** "TIP #43 EMBRACE REPETITION"


"Repetition is the single most powerful lever we have to improve our
skills, because it uses the built-in mechanism for making the wires of
our brains faster and more accurate"


"Moe Norman was a shy Canadian who played briefly on the professional
golf tour in the 1960s and ’70s. He was also, in most estimations, the
most accurate golfer in history. Norman shot seventeen holes in one,
three scores of 59, and, in Tiger Woods’s estimation, ranked as one of
two golfers in history who “owned their swing” (the other was Ben
Hogan). Norman was also a likely autistic who, at a young age, became
enraptured by the power of repetition. From the age of sixteen onward,
Norman hit eight hundred to a thousand balls a day, five days a week;
calluses grew so thick on his hands he had to pare them with a
knife. Because of his emotional struggles, Norman had difficulty
competing in tournaments. But at a demonstration in 1995, he hit
fifteen hundred drives in a row, all of them landing within fifteen
yards of each other. As Woods put it, Norman “woke up every day and
knew he was going to hit it well. Every day. It’s frightening how
straight he hits it.”"


"Embracing repetition means changing your mindset; instead of viewing
it as a chore, view it as your most powerful tool. As the martial
artist and actor Bruce Lee said, “I fear not the man who has practiced
ten thousand kicks once, but I fear the man who has practiced one kick
ten thousand times.”"


** "TIP #44 HAVE A BLUE-COLLAR MIND-SET"


"From a distance, top performers seem to live charmed, cushy
lives. When you look closer, however, you’ll find that they spend vast
portions of their life intensively practicing their craft. Their
mind-set is not entitled or arrogant; it’s 100-percent blue collar:
They get up in the morning and go to work every day, whether they feel
like it or not. As the artist Chuck Close says, “Inspiration is for
amateurs.”"


** "TIP #45 FOR EVERY HOUR OF COMPETITION, SPEND FIVE HOURS PRACTICING"


"A five-to-one ratio of practice time to performance time is a good
starting point; ten to one is even better."


** "TIP #46 DON’T WASTE TIME TRYING TO BREAK BAD HABITS—INSTEAD, BUILD NEW ONES"


"The solution is to ignore the bad habit and put your energy toward
building a new habit that will override the old one. A good example of
this technique is found in the work of the Shyness Clinic, a program
based in Los Altos, California, that helps chronically shy people
improve their social skills. The clinic’s therapists don’t delve into
a client’s personal history; "


"they don’t try to “fix” anything. Instead, they focus on building new
skills through what they call a social fitness model: a series of
simple, intense, gradually escalating workouts that develop new social
muscles. One of the first workouts for a Shyness Clinic client is to
walk up to a stranger and ask for the time. Each day the workout grows
more strenuous"


"To build new habits, start slowly. Expect to feel stupid and clumsy
and frustrated at first—after all, the new wires haven’t been built
yet, and your brain still wants to follow the old pattern. Build the
new habit by gradually increasing the difficulty, little by little. It
takes time, but it’s the only way new habits grow. For more insights
on this process, read The Power of Habit, by Charles Duhigg."


** "TIP #47 TO LEARN IT MORE DEEPLY, TEACH IT"


** "TIP #48" "GIVE A NEW SKILL A MINIMUM OF EIGHT WEEKS"


"When it comes to growing new skills, eight weeks seems to be an
important threshold. It’s the length of many top-level training
programs around the world, from the Navy SEALs’ physical-conditioning
program to the Meadowmount School of Music program to the clinics of
the Bolshoi Ballet to the mission training for the Mercury
astronauts. "


"Of course, this doesn’t mean that you can be proficient in any skill
in eight weeks. Rather, it underlines two more basic points: 1)
Constructing and honing neural circuitry takes time, no matter who you
are; and 2) Resilience and grit are vital tools, particularly in the
early phases of learning. Don’t make judgments too early. Keep at it,
even if you don’t feel immediate improvement. Give your talent (that
is, your brain) the time it needs to grow."


** "TIP #49 WHEN YOU GET STUCK, MAKE A SHIFT"


"We all know the feeling. You start out in a new skill, you progress
swiftly for a while, and then all of a sudden … you stop. Those are
called plateaus. "


"Research by Dr. K. Anders Ericsson, a professor of psychology at
Florida State University and coeditor of The Cambridge Handbook of
Expertise and Expert Performance, shows that the best way past a
plateau is to jostle yourself beyond it; to change your practice
method so you disrupt your autopilot and rebuild a faster, better
circuit. One way to do this is to speed things up—to force yourself to
do the task faster than you normally would."


"Or you can slow things down—going so slowly that you highlight
previously undetected mistakes. Or you can do the task in reverse
order, turn it inside out or upside down. It doesn’t matter which
technique you use, as long as you find a way to knock yourself out of
autopilot and into your sweet spot."


** "TIP #50 CULTIVATE YOUR GRIT"


"Grit is that mix of passion, perseverance, and self-discipline that
keeps us moving forward in spite of obstacles. It’s not flashy, and
that’s precisely the point. In a world in which we’re frequently
distracted by sparkly displays of skill, grit makes the difference in
the long run."


"Recently, a University of Pennsylvania researcher named Angela
Duckworth measured the influence of grit on twelve hundred first-year
West Point cadets before they began a brutal summer training course
called the Beast Barracks. Before the course began, she gave the
cadets a brief test: seventeen questions that asked them to rate their
own ability to stick to goals, to be motivated by failure, and to
persist in the face of obstacles. It turned out that this test—which
took about two minutes to complete—was uncannily accurate at
predicting whether or not a cadet succeeded, far exceeding West
Point’s complex set of predictive criteria, including IQ,
psychological test results, grade-point average, and physical
fitness. The grit test has since been used to predict success in
schools, business, and a variety of other settings."


"Grit isn’t inborn. It’s developed, like a muscle, and that
development starts with awareness. To take Duckworth’s test, do a
computer search for “Grit Survey” (or go directly to
www.​authentichappiness​.​sas.​upenn.​edu/​tests/​SameAnswers/​t.​aspx?​id=​1246). Take
the test and use your score as a way to reflect on the role of this
quality in your life"


"For instance, when you hit an obstacle, how do you react? Do you tend
to focus on a long-term goal, or move from interest to interest? What
are you seeking in the long run? Begin to pay attention to places in
your life where you’ve got grit, and celebrate them in yourself and
others."


** "TIP #51 KEEP YOUR BIG GOALS SECRET"


"Telling others about your big goals makes them less likely to happen,
because it creates an unconscious payoff—tricking our brains into
thinking we’ve already accomplished the goal. Keeping our big goals to
ourselves is one of the smartest goals we can set."


** "TIP #52 “THINK LIKE A GARDENER, WORK LIKE A CARPENTER”"


"To do this, it helps to “think like a gardener and work like a
carpenter.” I heard this saying at Spartak. Think patiently, without
judgment. Work steadily, strategically, knowing that each piece
connects to a larger whole."


"Deep practice (n), also called deliberate practice: The form of
learning marked by 1) the willingness to operate on the edge of your
ability, aiming for targets that are just out of reach, and 2) the
embrace of attentive repetition."


"Ignition (n): The motivational process that occurs when your identity
becomes linked to a long-term vision of your future. Triggers
significant amounts of unconscious energy; usually marked by the
realization That is who I want to be."


"Reach (v): The act of stretching slightly beyond your current
abilities toward a target, which causes the brain to form new
connections. Reaching invariably creates mistakes, which are the
guideposts you use to improve the next attempt."


"Rep (n, abbreviation for repetition): The act of attentively
repeating an action, often with slight variances at gradually
increasing difficulty, which causes the brain’s pathways to increase
speed and improve accuracy."


"Shallow practice (n): The opposite of deep practice, marked by lack
of intensity, vagueness of goal, and/or the unwillingness to reach
beyond current abilities. Often caused by an aversion to making
mistakes; results in vastly slowed skill acquisition and
learning. Sweet spot (n): The zone on the edge of current ability
where learning happens fastest. Marked by a frequency of mistakes, and
also by the recognition of those mistakes (see Tip #13)."

* The Art of Learning_ A Journey in the Pursuit of Excellence Josh Waitzkin


When aiming for the top, your path requires an engaged, searching mind. You have
to make obstacles spur you to creative new angles in the learning process. Let
setbacks deepen your resolve. You should always come off an injury or a loss
better than when you went down. Another angle on this issue is the unfortunate
correlation for some between consistency and monotony.

It is all too easy to get caught up in the routines of our lives and to lose
creativity in the learning process. Even people who are completely devoted to
cultivating a certain discipline often fall into a mental rut, a disengaged
lifestyle that implies excellence can be obtained by going through the motions.
We lose presence. Then an injury or some other kind of setback throws a wrench
into the gears. We are forced to get imaginative.

Most people would be surprised to discover that if you compare the thought
process of a Grandmaster to that of an expert (a much weaker, but quite
competent chess player), you will often find that the Grandmaster consciously
looks at less, not more. That said, the chunks of information that have been put
together in his mind allow him to see much more with much less conscious
thought. So he is looking at very little and seeing quite a lot. This is the
critical idea.

** The Power of Presence

Grandmasters know how to make the subtlest cracks decisive. The only thing to do
was become immune to the pain, embrace it, until I could work through hours of
mind-numbing complexities as if I were taking a lovely walk in the park.

The vise, after all, was only in my head. I spent years working on this issue,
learning how to maintain the tension—becoming at peace with mounting pressure.
Then, as a martial artist, I turned this training to my advantage, making my
opponents explode from mental combustion because of my higher threshold for
discomfort.

In every discipline, the ability to be clearheaded, present, cool under fire is
much of what separates the best from the mediocre. In competition, the dynamic
is often painfully transparent. If one player is serenely present while the
other is being ripped apart by internal issues, the outcome is already clear.
The prey is no longer objective, makes compounding mistakes, and the predator
moves in for the kill. While more subtle, this issue is perhaps even more
critical in solitary pursuits such as writing, painting, scholarly thinking, or
learning.

In the absence of continual external reinforcement, we must be our own monitor,
and quality of presence is often the best gauge. We cannot expect to touch
excellence if “going through the motions” is the norm of our lives. On the other
hand, if deep, fluid presence becomes second nature, then life, art, and
learning take on a richness that will continually surprise and delight. Those
who excel are those who maximize each moment’s creative potential—for these
masters of living, presence to the day-to-day learning process is akin to that
purity of focus

others dream of achieving in rare climactic moments when everything is on the
line.

The secret is that everything is always on the line. The more present we are at
practice, the more present we will be in competition, in the boardroom, at the
exam, the operating table, the big stage. If we have any hope of attaining
excellence, let alone of showing what we’ve got under pressure, we have to be
prepared by a lifestyle of reinforcement. Presence must be like breathing.

** Searching for the Zone

How can I learn to enter the zone at will, make it a way of life? How can I
maintain my focus under pressure, stay serene and principled under fire,
overcome distraction? What do I do when my emotions get out of control?

The physiologists at LGE had discovered that in virtually every discipline, one
of the most telling features of a dominant performer is the routine use of
recovery periods.

Players who are able to relax in brief moments of inactivity are almost always
the ones who end up coming through when the game is on the line. This is why the
eminent tennis players of their day, such as Ivan Lendl and Pete Sampras, had
those strangely predictable routines of serenely picking their rackets between
points, whether they won or lost the last exchange, while their rivals fumed at
a bad call or pumped a fist in excitement. Consider Tiger Woods, strolling to
his next shot, with a relaxed focus in his eyes. Remember Michael Jordan sitting
on the bench, a towel on his shoulders, letting it all go for a two-minute break
before coming back in the game? Jordan was completely serene on the bench even
though the Bulls desperately needed him on the court. He had the fastest
recovery time of any athlete I’ve ever seen.

In the coming months, as I became more attuned to the qualitative fluctuations
of my thought processes, I found that if a think of mine went over fourteen
minutes, it would often become repetitive and imprecise.

After noticing this pattern, I learned to monitor the efficiency of my thinking.
If it started to falter, I would release everything for a moment, recover, and
then come back with a fresh slate. Now when faced with difficult chess
positions, I could think for thirty or forty minutes at a very high level,
because my concentration was fueled by little breathers.

At LGE, they made a science of the gathering and release of intensity, and found
that, regardless of the discipline, the better we are at recovering, the greater
potential we have to endure and perform under stress.

At LGE they had discovered that there is a clear physiological connection when
it comes to recovery—cardiovascular interval training can have a profound effect
on your ability to quickly release tension and recover from mental exhaustion.

If you are interested in really improving as a performer, I would suggest
incorporating the rhythm of stress and recovery into all aspects of your life.
Truth be told, this is what my entire approach to learning is based on—breaking
down the artificial barriers between our diverse life experiences so all moments
become enriched by a sense of interconnectedness.

So, if you are reading a book and lose focus, put the book down, take some deep
breaths, and pick it up again with a fresh eye. If you are at work and find
yourself running out of mental stamina, take a break, wash your face, and come
back renewed.

The unconscious mind is a powerful tool, and learning how to relax under
pressure is a key first step to tapping into its potential.

Interval work is a critical building block to becoming a consistent long-term
performer. If you spend a few months practicing stress and recovery in your
everyday life, you’ll lay the physiological foundation for becoming a resilient,
dependable pressure player. The next step is to create your trigger for the
zone.

Not only do we have to be good at waiting, we have to love it. Because waiting
is not waiting, it is life. Too many of us live without fully engaging our
minds, waiting for that moment when our real lives begin. Years pass in boredom,
but that is okay because when our true love comes around, or we discover our
real calling, we will begin. Of course the sad truth is that if we are not
present to the moment, our true love could come and go and we wouldn’t even
notice. And we will have become someone other than the you or I who would be
able to embrace it. I believe an appreciation for simplicity, the everyday—the
ability to dive deeply into the banal and discover life’s hidden richness—is
where success, let alone happiness, emerges.

Along these lines, when considering the issue of performance state, it is
important to avoid focusing on those rare climactic moments of high-stakes
competitive mayhem. If you get into a frenzy anticipating the moment that will
decide your destiny, then when it arrives you will be overwrought with
excitement and tension. To have success in crunch time, you need to integrate
certain healthy patterns into your day-to-day life so that they are completely
natural to you when the pressure is on. The real power of incremental growth
comes to bear when we truly are like water, steadily carving stone. We just keep
on flowing when everything is on the line.

I had learned from Jack Groppel at LGE to eat five almonds every forty-five
minutes during a long chess game, to stay in a steady state of alertness and
strength.

** Making Sandals

To walk a thorny road, we may cover its every inch with leather or we can make
sandals.

I had to develop the habit of taking on my technical weaknesses whenever someone
pushed my limits instead of falling back into a self-protective indignant pose.
Once that adjustment was made, I was free to learn. If someone got into my head,
they were doing me a favor, exposing a weakness. They were giving me a valuable
opportunity to expand my threshold for turbulence. Dirty players were my best
teachers.

In my experience the greatest of artists and competitors are masters of
navigating their own psychologies, playing on their strengths, controlling the
tone of battle so that it fits with their personalities.



* what are the best situations to use pros/cons solving method?
I think when you want to choose between two options.
