#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/main.css" />
* How much time is too much (to put into a single problem)?
I would consider having more than one problem 'on the go' at a
time. Similar to the concept often repeated at school before exams,
"if you get stuck on a problem, move on and come back to it
later". There are two clear benefits I can see to this approach:

 - *You find the answer to the problem you're stuck on by solving a new problem.*
 - Over the passage of time, the answer to your problem finds its way into your brain through the ether.

http://math.stackexchange.com/questions/232632/how-much-time-is-too-much-to-put-into-a-single-problem
http://math.stackexchange.com/questions/689214/some-questions-regarding-preparing-for-math-olympiads-searched-but-didnt-get-a

 1) Read the problem completely twice.
 2) Solve the problem manually with 3 sets of sample data.
 3) Optimize the manual steps.
 4) Write the manual steps as comments or pseudo-code.
 5) Replace the comments or pseudo-code with real code.
 6) Optimize the real code.

https://simpleprogrammer.com/2011/01/08/solving-problems-breaking-it-down/
* technique

| technique                        | description                                                                     |
|----------------------------------+---------------------------------------------------------------------------------+
| Divide-and-conquer               | Can you divide the problem into two or more smaller independent subproblems and |
|                                  | solve the original problem using solutions to the subproblems?                  |
| Recursion , dynamic programmming | If you have access to solutions for smaller in- stances of a given problem,     |
|                                  | , can you easily con- struct a solution to the problem?                         |

* general strategies
** Exhaustive Search
Theoretically, many puzzles can be solved by exhaustive search—a
problem-solving strategy that simply tries all possible candidate
solutions until a solution to the problem is found.  

The most important limitation of exhaustive search is its
inefficiency.as a rule, the number of solution candidates that need to
be processed grows at least exponentially with the problem size,
making the approach inappropriate not only for a human but often for a
computer as well.

*** cons
****  Mechanics of generating all possible solution candidate
For some problems, such candidates compose a well-structured set. For
example, candidate arrangements of the first nine positive integers in
the cells of the 3 × 3 table (see the Magic Square example above) can
be obtained as permutations of these numbers, for which several
algorithms are known. There are many problems, however, where solution
candidates do not form a set with such a regular structure.

**** The more fundamental, difficulty lies in the number of solution candidates that need to be generated and processed

Typically, the size of this set grows at least exponentially with the
problem size. Therefore, exhaustive search is practical only for very
small instances of such problems.

** Backtracking
Backtracking is an important improvement over the brute-force approach
of exhaustive search. *It provides a convenient method for generating*
*candidate solutions while making it possible to avoid generating*
*unnecessary candidates.* The main idea is to construct solutions one
component at a time and evaluate such partially constructed candidates
as follows: If a partially constructed solution can be developed
further without violating the problem’s constraints, it is done by
taking the first remaining legitimate option for the next
component. If there is no legitimate option for the next component, no
alternatives for any remaining component need to be considered. In
this case, the algorithm backtracks to replace the last component of
the partially constructed solution with the next option for that
component.


Typically, backtracking involves undoing a number of wrong choices—the
smaller this number, the faster the algorithm finds a
solution. Although in the worst-case scenario a backtracking algorithm
may end up generating all the same candidate solutions as an
exhaustive search, this rarely happens.

It is convenient to interpret a backtracking algorithm as a process of
constructing a tree that mirrors decisions being made. Computer
scientists use the term tree to describe hierarchical structures such
as family trees and organizational charts. A tree is usually shown
with its root (the only node without a parent) on the top and its
leaves (nodes without children) on or closer to the bottom of the
diagram. This is nothing but a convenient typographical convention,
however. For a backtracking algorithm, such a tree is called a
state-space tree. The root of a state-space tree corresponds to the
start of a solution construction process; we consider the root to be
on the zero level of the tree. The root’s children—on the first level
of the tree—correspond to possible choices of the first component of a
solution (e.g., the cell to contain 1 in the magic square
construction). Their children—the nodes on the second level—correspond
to possible choices of the second component of a solution, and so
on. Leaves can be of two kinds. The first kind—called nonpromising
nodes or dead ends—correspond to partially constructed candidates that
cannot lead to a solution. After establishing that a particular node
is nonpromising, a backtracking algorithm terminates the node (the
tree is said to be pruned), undoes the decision regarding the last
component of the candidate solution by backtracking to the parent of
the nonpromising node, and considers another choice for that
component. The second kind of a leaf provides a solution to the
problem. If a single solution suffices, the algorithm stops; if other
solutions need to be searched for, the algorithm continues searching
for them by backtracking to the leaf’s parent.

* TRIZ

** Inventive Principle 1: Segmentation

    Divide an object into independent parts
        Flat-pack furniture
        Segmented tent poles
        Sales teams have different markets/geographical areas
    Make an object easy to take apart
        Quick-release bicycle wheels
        Use contract workers instead of permanent employees
    Make the object even more fragmented or segmented
        Many small, local offices rather than one large HQ
        Telecommute: employees work from home

** Inventive Principle 2: Taking Out

    Take out a problem
        Air conditioning in the room, noise elsewhere
        Light pipes: get light where needed without heat
    Only get what you need
        Scarecrow
        Buy-in expertise
        No-frills hotel

** Inventive Principle 3: Local Quality

    Change an object from uniform to non-uniform
        Ergonomic knife handles
        Offer different products or use different marketing strategies for different geographical markets
    Change the environment from uniform to non-uniform.
        Working hours phased to accommodate people working on international, shifted time-zone projects
    Make each part of an object function in conditions most suitable for its operation
        Night-time adjustment on rear-view mirror
    Make each part of an object fulfil a different and useful function
        Hammer with nail-puller

** Inventive Principle 4: Asymmetry

    Change the shape of an object from symmetrical to asymmetrical
        Funnel with off-set exit for faster flow rate
        Use a different marketing approach for different types of clients
    Change the shape of an object to suit external asymmetries
        Ergonomic running shoes
    If an object is asymmetrical, make it more asymmetrical
        Different running shoes to suit users’ running styles

** Inventive Principle 5: Merging

    Join objects or operations together
        Bi-focal lenses
        Crew members in McDonalds
    Join parallel operations in time
        Include your customers and suppliers in design phase
        Work on a project in parallel rather than in series

** Inventive Principle 6: Multi-Function

    Make an object perform multiple functions; eliminate the need for other objects.
        Swiss Army Knife
        ‘One-stop shopping’ – supermarkets sell insurance, banking services, fuel, newspapers and so on.

** Inventive Principle 7: Nested Doll

    One object is placed inside another; which, in turn, is inside another, and so on.
        Shopping centres/malls
        Nested tables
        Measuring cups or spoons
    One object passes through another
        Telescopic car aerial
        Tape measure

** Inventive Principle 8: Counterweight

    Compensate for the weight of an object by joining it with another object which provides lift.
        Hot-air balloons
        Kayaks with integrated foam floats
        Build teams of different personality types
    Compensate for the weight of an object by making it interact with the environment
        Maglev trains use magnetic levitation to create lift and propulsion, reducing friction and allowing for higher speeds
        Use renewable energy to reduce a company’s carbon footprint
        Boost popularity by connecting with popular causes; for example, charities

** Inventive Principle 9: Prior Counteraction

    Add a counteraction to manage a downside
        Make clay pigeons out of ice or clay
        Off-set carbon emissions
        Give generous severance packages when making redundancies
    Create beforehand stresses in an object that will oppose known undesirable working stresses later on
        Pre-stressed concrete compensates for concrete’s weakness in tension
        Ergonomically assess workstations

** Inventive Principle 10: Prior Action

    Do a required action in advance
        Practise emergency procedures in advance of crisis
        Agree meeting agendas in advance
        Arrange objects conveniently so they can go into action without loss of time
        Just-In-Time production
        In-store bakeries

** Inventive Principle 11: Cushion in Advance

    Prepare emergency means beforehand to compensate for the relatively low reliability of an object
        Back up computer data
        Contingency planning
        Have more than one person trained in skills critical to the company

** Inventive Principle 12: Equal Potential

    Change the conditions of work so that an object doesn’t need to be raised or lowered
        Mechanic’s pit in garage (car isn’t lifted)
        Grow the job rather than promote the person

** Inventive Principle 13: The Other Way Round

    Do the opposite action
        Cash-back in stores: customers take money away instead of security firms
    Make movable parts fixed, and fixed parts movable
        Home-shopping
        Treadmills
        Wind tunnels
    Turn the object upside down
        Customers create their own product, for example, radio listeners dialling in for talk shows or to give traffic updates
        Tomato sauce bottle with opening on the bottom

** Inventive Principle 14: Spheres and Curves

    Switch from flat surfaces to spherical ones; from parts shaped as cubes or rectangles to ball-shaped structures
        Mezzaluna (knife shaped as a half-moon)
        Arches and domes for strength in architecture
        360-degree appraisals
    Use rollers, balls, spirals, domes
        Rotary pizza cutter
        Ballpoint pens
        Archimedes screw
        Make repeat purchases easy (such as direct debits, subscriptions)
    Go from linear to rotary motion, use centrifugal forces
        Push–pull to rotary switches (for example, lighting dimmer switches)
        Loyalty schemes

** Inventive Principle 15: Dynamism

    Change the object or environment to work the best at every stage of work
        Adjustable steering wheel (or seat, back support, mirror position and so on)
        Different price and positioning for products throughout their life
    Divide an object into parts that can move relative to each other
        Bifurcated bicycle saddles
        Folding chairs
    If an object is rigid, make it movable
        Bendy drinking straw
        Hot-desking
        Virtual 360-degree tours online

** Inventive Principle 16: Partial or Excessive Action

    If it’s difficult to get 100 per cent of an action, go for more or less
        Overfill bottles on production line
        Overspray when painting, then remove the excess
        Ensure happy customers by providing exceptional customer service
        Show products and services online even if it’s not possible to purchase online

** Inventive Principle 17: Another Dimension

    Move to another dimension: from one to two or three dimensions
        Coiled telephone wire/garden hose
    Go from a single layer to multi-layers
        Multi-storey car park
        Hierarchy of command
    Tilt an object or turn it on its side
        Cars on road transporter inclined to save space
    Use the other side of an object
        Print on both sides of paper
        Electronic components mounted on both sides of circuit board

** Inventive Principle 18: Mechanical Vibration

    Make an object vibrate
        Electric toothbrushes
    Increase the frequency of vibration (up to ultrasonic)
        Sonic toothbrushes
        Sonic facial brushes
    Use an object's resonant frequency
        Break up kidney stones with ultrasound
        Tuning fork
        Use piezoelectric vibrators instead of mechanical ones
        Quartz watches
    Use combined ultrasonic and electromagnetic field oscillations together
        Ultrasonic and electromagnetic pest repellers deter both mice and insects

** Inventive Principle 19: Periodic Action

    Go from continuous action to periodic or pulsating actions
        ABS brakes
        Flashing bicycle lights
        Change leadership: many university heads of department only lead for a year, senior academics rotate leadership
    If an action is already periodic, change the rate or level of change
        Appraise performance more regularly than annual reviews
    Use pauses between actions to perform a different action
        Perform maintenance work during slow periods
        Inkjet printer cleans head between passes

** Inventive Principle 20: Continuous Useful Action

    Carry out work without a break
        24-hour manufacturing
        Hospital emergency departments
    Remove idle or intermittent actions
        Kayaks use double-ended paddle to utilise recovery stroke
        Multi-skill workforce to enable them to perform other tasks when their core job has quiet periods

** Inventive Principle 21: Rushing Through

    Do a process, or certain stages (which are harmful or dangerous) at high speed
        Cut plastic faster than heat can propagate in the material, to avoid deforming the shape
        Immediate dismissal

** Inventive Principle 22: Blessing in Disguise

    Use harmful factors (particularly, harmful effects of the environment) to get something good
        Pain can be useful feedback to stop doing something; for example, walk on broken ankle
    Remove a harmful action by adding another harmful action
        Reduce traffic in cities by introducing a congestion charge
    Increase a harmful factor so much that it is no longer harmful
        Restrict supply of goods to create scarcity value (such as designer handbags)

Inventive Principle 23: Feedback

    Introduce feedback
        Customer surveys
        Feedback forms after training
        Exercise apps that inform you of distance run, average speed, calories burned
    If feedback is already used, make it more effective
        Go from paper feedback forms to interviews or online surveys
        Share information from exercise apps on social media

** Inventive Principle 24: Intermediary

    Use an intermediary object to pass on an action
        Play guitar with a plectrum
        Marriage counsellor
        Travel agent
    Temporarily join an object with another (easily removable)
        Oven gloves for hot dishes
        Bridging loans
        ‘The A-Team’

** Inventive Principle 25: Self-service

    An object services, maintains and repairs itself
        Self-cleaning ovens
        Wikipedia
        Customer loyalty reward schemes (such as Nectar cards) collect information about individual’s purchasing decisions to target services and products
        Bicycle tyres filled with gel to seal punctures instantly
    Use waste (or lost) resources, energy or substances.
        Use heat from a process to generate electricity (co-generation)
        Use travel time to work

** Inventive Principle 26: Copying

    Replace unavailable, expensive, complicated, fragile objects with cheap, simple copies
        Scan rare, historic books and documents, so they are accessible to all and the original remains protected
    Replace an object, or process with optical copies
        Measure an object from a photograph
        Product manuals as PDFs rather than printed booklets
        Online training instead of classroom training
    If visible optical copies are used, move to infrared or ultraviolet; use unusual ways of seeing/viewing situations
        Police helicopters use infrared to track suspects
        Evaluate customer satisfaction in multiple ways, for example, interviews, questionnaires, observing customers use product

** Inventive Principle 27: Cheap, Short-Living Objects

    Replace an expensive object with many inexpensive objects that don’t last as long
        Disposable serviettes, napkins, cups, cameras
        Automate work procedures and have low-skilled, low-paid staff who are easily replaceable
        Make product cheap and easily replaceable instead of reusable, for example, contact lenses, nappies, low-cost clothes

** Inventive Principle 28: Replace Mechanical System

    Replace a mechanical system with a sensory one (optical, acoustic, taste or smell)
        Lights and bells rather than secure barriers at rail crossings
        Smell of baking bread to entice shoppers
        Security systems
    Use electric, magnetic and electromagnetic fields to interact with the object; use influence instead of rules
        Magnetic bearings
        TV remote control
        Use staff loyalty to encourage good behaviour
    Replace stationary fields with moving unstructured fields; replace unstructured fields with structured ones
        Hot desking
        GPS sensors inform central control point of location of delivery vans, taxis
    Use fields in conjunction with field-activated (such as ferromagnetic) particles
        Ultrasonic welding

** Inventive Principle 29: Pneumatics and Hydraulics

    Use gas and liquid parts of an object instead of solid parts (for example, inflatable, filled with liquids, air cushion, hydrostatic, hydro-reactive); use flexible influences instead of solid rules
        Inflatable mattresses
        Hovercraft
        Use guidelines, not rules
        Create a ‘health and safety culture’ instead of a long list of rules

** Inventive Principle 30: Flexible Membranes and Thin Films

    Use flexible shells and thin films instead of three-dimensional structures
        Tarpaulin car cover instead of garage
        Open-plan offices
    Isolate the object from the external environment using flexible shells and thin films
        Bubble-wrap
        Bandages and plasters
        Offices with cubicles

** Inventive Principle 31: Porous Materials

    Make an object porous or add porous elements (inserts, coatings and so on)
        Cavity wall insulation
        Foam metals
        ‘Open door’ management policies
    If an object is already porous, use the pores to introduce a useful substance or function
        Medicated dressings
        Train customer service teams to sell additional products and services (for example, at shop tills)

** Inventive Principle 32: Colour Change

    Change the colour of an object or its surroundings
        Colour-changing paint or sun cream
        Light-sensitive glasses
    Change the transparency of an object or its surroundings
        Make organisation’s objectives and decision-making processes clear to everyone
        Transparent solar cells (make every window/screen a photovoltaic solar cell)
    Observe objects or processes that are hard to see by using coloured additives
        Use opposing colours to increase visibility (for example, butchers use green decoration to make meat look redder)
    If additives are already used, monitor things that are hard to see by adding luminescence/other markers
        UV marker pens to identify stolen goods (only seen under ultraviolet light)
        Get potential customers to register interest with special offers

** Inventive Principle 33: Uniform Material

    Objects interacting with the main object should be made of the same material (or one with similar properties)
        Ice cubes made of drink they are cooling (such as lemonade)
        Wood dowel joints for joining wooden components
        Make sure all your employees can understand and sell your products
        ‘Mirror’ someone’s body language to facilitate easy communication

** Inventive Principle 34: Discarding and Recovering

    Make objects (or part of them) that have fulfilled their useful functions go away (discard by dissolving, evaporating and so on) or modify them directly during operation
        Dissolving capsules for vitamins and medicine
        Bio-degradable containers and bags
        Take on temporary staff to manage busy periods, such as in shops over Christmas
    Restore consumable parts of an object during operation
        Sell on to ‘used up’ customer: for example, transfer student bank accounts to graduate bank accounts when they finish their course; dentists refer patients to dental hygienists
        Self-sharpening blades
        Mechanical pencil

** Inventive Principle 35: Parameter Change

    Change the physical state (for example, to a gas, liquid or solid)
        Transport gases as liquids
        Liquid soap instead of soap bar
        Deodorant as a liquid, solid stick or aerosol spray
        Virtual organisations
        Customer service offered remotely (by phone or chat box online) instead of face to face
    Change the concentration or density
        Change number of staff
        Fire briquettes: low density for lighting fires, high density for burning all night
        Move from local to centralised distribution (or vice versa)
    Change the degree of flexibility
        Vulcanised rubber is less flexible and stronger
        Hot-desking
        Flexi-time
    Change the temperature or volume
        ‘Fire up’ and motivate employees
        Increase individual’s scope of responsibility
        Heated butter knives and ice cream scoops
        Butter knives with built-in grater to soften cold butter
    Change the pressure
        Pressure cooking is faster
        Manipulate stress levels (increase near deadlines)
    Change other parameters
        Semco: staff set their own wages, production targets, working hours
        Thixotropic paints are viscous so they don’t drip, but become runny when shear force is applied by the brush against the surface being painted.

** Inventive Principle 36: Phase Changes

    Use phenomena occurring during phase changes (volume changes, loss of absorption of heat and so on)
        Latent heat effects in melting or boiling
        Break rocks by soaking in water and then freezing
        Individuals try harder when proving themselves; for example, graduates, new to the post, newly promoted: use these people for difficult projects/those requiring long hours

** Inventive Principle 37: Thermal Expansion

    Use expansion (or contraction) of materials by heat; responsiveness to circumstances
        Be very responsive to change; for example, have extra staff available for busy periods
        Emergency services available to deal with crises
        Shape memory materials
        Shrink-wrapping
    Use multiple materials with different coefficients of thermal expansion; use multiple and different systems that respond to circumstances differently
        Bi-metallic strips used in thermostats
        Different emergency services offer different expertise in major car crashes, for example, police create safe space on road and prevent other crashes; fire service to cut people out of cars; ambulance knows how to move injured people.

** Inventive Principle 38: Boosted Interactions

    Enrich the atmosphere
        Create a competitive atmosphere to motivate sales team
        Oxygen tent for asthmatic patients
        Nitrous oxide injection for power boost in engines
        Create the right atmosphere for different working environments: places with buzz for team working and discussing ideas; quiet zones for independent working
    Create a highly enriched atmosphere
        Use highly charismatic leaders to engage the workforce
        Irradiation of food to extend shelf life
    Enrich the atmosphere with unstable elements
        Staff charged with energy through uncertainty: such as fear (threat of redundancy) or rewards (bonuses/promotion)
        Use ozone to destroy micro-organisms

** Inventive Principle 39: Inert Atmosphere

    Replace a normal environment with an inert one
        Libraries’ quiet environment creates a good environment to work, read and study
        Corporate away days
        Foam to separate a fire from oxygen
    Add neutral parts or inert additives to an object
        Use contractors and external consultants
        Fire retardant additives

** Inventive Principle 40: Composite Structures

    Change from uniform to layered/composite (multiple) structures
        Teams with diverse team members bring different skills and perspectives
        Use different delivery methods in training (lectures, exercises, follow-up reading)
        Fibre-reinforced composite materials in Boeing 787 wing and fuselage
        Concrete aggregate

* strategies for effective problem solving
** GETTING IN THE RIGHT FRAME OF MIND
People who are effective problem solvers develop mind sets and habits
which aid them in dealing with difficult problems. Stephen Covey's research on
highly effective people revealed that there are certain habits these people practice.
The seven habits you should consider developing are shown in the table below.

*Habit 1 Be Proactive.* Take the initiative and make things happen. Aggressively seek
new ideas and innovations. Don't let a negative environment affect your
behavior and decisions. Work on things that you can do something about. If
you make a mistake, acknowledge it and learn from it.

*Habit 2 Begin with the End in Mind.* Know where you are going and make sure all
the steps you take are in the right direction. First determine the right things
to accomplish and then how to best accomplish them. Write a personal mission
statement describing where you want to go and what you want to be and how
to accomplish these things.

*Habit 3 Put First Things First.* List your top priorities each day for the upcoming
week and schedule time to work on them. Continually review and prioritize
your goals. Say NO to doing unimportant tasks. Focus on the important tasks,
the ones that will have impact if carefully thought out and planned.

*Habit 4 Think Win/Win.* Win/Win is the frame of mind that seeks mutual benefits
for all people involved in solutions and agreements. Identify the key issues
and results that would constitute a fully acceptable solution to all. Make all
involved in the decision feel good about the decision and committed to a plan
of action.

*Habit 5 Seek First to Understand, Then to Be Understood.* Learn as much as you
can about the situation. "Listen, listen, listen." Try to see the problem from
the other person's perspective. Be willing to be adaptable in seeking to be
understood. Present things logically, not emotionally. Be credible, empathetic,
and logical.

*Habit 6 Synergize*. Make the whole greater than the sum of its parts. Value the
differences in the people you work with. Foster open and honest
communication. Help everyone bring out the best in everyone else.

*Habit 7 Renewal*. Renew the four dimensions of your nature:
 - Physical: Exercise, nutrition, stress management.
 - Mental: Reading, thinking, visualizing, planning, writing.
 - Spiritual: Value clarification and commitment, study and meditation.
 - Social/Emotional: Service, empathy, self-esteem, synergy.

* Stop Guessing 
** "Stop Guessing "
*** intro
"Truly solving the problem involves understanding what’s wrong and why it
happened, through investigation and understanding—not by spending days or weeks
testing different guesses until, hopefully, one works."

*** "WHY GUESSING FAILS "

"Through both nature and nurture, guessing has become a foundation of our
problem-solving skill set. And guessing helps us resolve many of our problems,
but only the easy ones. "

"Then you’ve got hard problems. These are the kinds of problems that might
have hundreds or thousands of potential causes. "

"When you’re facing a problem of moderate difficulty, there may be something
like 50 potential root causes. "

"Any time you “come up with” many things to check that could be the cause, you
are guessing"

"First, you’ve reinforced the habit of guessing in your mind or in your
organization, fooled yourself into thinking it’s a good strategy and is going to
work again"

"Second, you haven’t developed a deeper understanding of whatever you’re trying
to fix, whether it’s yourself, a process, or a machine. Instead of spending time
building some knowl- edge of the fundamentals that you can use in the future—new
problems are popping up all the time—you’ve spent your time guessing and
checking. So next time there’s a problem, you’re back to square one. "

*** "THE CURSE OF LUCK"

"let’s say you guess, and you get lucky: You found a solution and implemented it
effectively. You may or may not have spent a lot of time and resources on it.
Unfortunately, some bad side effects come with this rare victory."

"Third, and perhaps most importantly, you’re not becoming a better
problem-solver. While guessing might eventually get the job done for problems of
moderate difficulty (although at great cost), you rob yourself or your team of
critical skills development. "

" When you get to truly hard problems, you’re going to need all of the skill you
can get: If you don’t practice using the right behaviors and method to solve
moderate problems then you will never master them, and you’re going to get
shellacked when you try to tackle the hard ones. "

*** "GUESSING IN POPULAR PROBLEM-SOLVING METHODS "

"When you look at most popular problem-solving approaches, you’ll find that they
devolve into structured-guessing at some point. Many have steps such as,
“develop possible root causes” or “deduce probable causes.” Whenever we develop
some list of possible root causes, we’re guessing, even if it’s structured
guessing. Some of these guessing steps are disguised as “forming hypotheses” or
other seemingly scientific approaches. Many of these methods are designed to
focus on simple problems quickly, where one needs to just organize guesses—Five
Whys is great for this. For hard problems, though, the likelihood that you’ll
include the true root cause in the list of “possible root causes” that you guess
is tiny. "

*** "DEALING WITH GUESSING "

"If you or your team seem are distracted by guessing, I’ve found it useful not
to suppress it but to write it down and get it out of your system. Put it in an
envelope and ignore it. If"

"Great problem-solvers resist the temptation to guess at every stage of the
process. Guessing is a tough habit to break, so get started! "

*** "IT’S NATURAL TO GUESS, AND YOU CAN STOP "

** "Smell the Problem "

*** "HOW TO SMELL WELL "

"Early on you’ll want to smell the problem to develop a pattern of failure.
Where possible, understanding where the problem does and doesn’t happen, when
the problem started, and how often the problem occurs will generate critical
insights for the problem-solving effort. For easy or fairly moderate problems,
this pattern of failure can lead to the key insight that solves the problem or
puts you just one step away. "

"Table 2.1: Questions to ask when smelling the problem. What does the problem
look like? If you look closely, is it always the same every time? When did you
first see the problem? What pattern do you notice if you look at the problem
over time? Where might you expect to see the same problem but don’t? "

*** "DEVELOPING A PATTERN OF FAILURE "

"There are problem-solving methods that can help us add rigor and practice. They
ask thought-provoking questions that guide you to collect information and look
for very specific patterns, rather than shotgunning and looking at everything in
the system. "

"I can provide some basic guidance on where to get started in developing a
strong pattern of failure (see Table 2.1). Most gen- erally, describe in detail
the conditions in which a problem does and does not occur."

"Great problem-solvers will overcome barriers to getting the specific
information they need. If a machine is moving too quickly for a problem-solver
to see a pattern with their own eyes, a great problem-solver will get a camera
to record it, and then slow it down. If a manufacturing line doesn’t
automatically count units produced, great problem-solvers get out there and do
the counting. They work closely with those who best understand the system or
process to find where to look to answer each ques- tion and find the clearest
information"

"All of the questions in Table 2.1 are guides, not directions. Look at one
occurrence and many together, when possible, and see what you discover. Again,
you are not trying to guess the solution. You are simply trying to understand
the facts of how the failure manifests. "

"smelling: You’ll have new understanding to ask new questions. This isn’t a
step: It’s a behavior. Smell the problem to answer questions about it that
arise."

*** "HOW MUCH IS ENOUGH? "

"Developing a thorough problem description and pattern of failure is not a
matter of gathering reams of data and burying yourself with them"

"Great problem solvers develop the questions that they want to answer before
they go about collecting information and data, rather than depending on whatever
data streams they see. They grab the signal, not the noise."

"But when are you done with describing the problem or develop- ing a pattern of
failure? In short: never. As you develop insight and dig into the fundamentals,
you’ll be coming back iteratively to keep "

** "Embrace Your Ignorance"
*** intro
"and that when they walk into a new situation they must be more focused on
learning what they do not yet know than demonstrating the knowledge they already
have. They ask questions others might think are stupid, and challenge what
“everyone knows” to make sure they have the facts."

"Embracing one’s ignorance isn’t easy. In many cases we already know 90% of what
is required to solve a problem, so it’s reason- able to start from a position of
knowledge rather than ignorance: People are asking you to solve the problem
because of what you know, rather than what you don’t. However, it is the last
10% that lies between you and an elegant solution. "

"Great problem-solvers know that they must become masters of the unique problem
and the process it affects, "

*** "EMBRACE YOUR IGNORANCE, THEN SLAY IT "

"A great problem-solver will gently challenge the organiza- tion rather than
individuals, and have the humility to lead by example, by demonstrating their
ignorance. "

"Moving towards the true cause of a problem is going to require fresh eyes that
want to learn. This is why outside problem-solv- ers sometimes have an advantage
with hard problems over those familiar with the system: A common cognitive bias
is the “curse of knowledge,” where our brains assume that the problem we’re
looking at is similar to something we’ve seen in the past. "

"Great problem-solvers aren’t afraid of their ignorance, and they’re not afraid
of others seeing it. Great questions shatter assumptions, provoke new insight,
and position those"

"that do know about the process or system to contribute their expertise. Great
problem-solvers build confidence and don’t need to position themselves as
all-knowing "

"But great problem-solvers don’t just admit their igno- rance. They embrace it.
They understand that introducing a little bit of smart ignorance into a
problem-solving effort will get people asking questions for which they assumed
they already had answers. "

** "Know What Problem You’re Solving "
*** intro
"Successfully solving hard problems requires knowing what problem you’re
solving. You should put great care into defin- ing the problem in an accurate
and precise way, as a direct and measurable observation of the problem. It must
be clear how solving it translates directly to your goals. And it must abso-
lutely not be an assumption or jump-to-conclusion. "

*** "THE DANGER OF BAD PROBLEM DEFINITIONS "

"Great problem-solvers avoid being trapped into solving the wrong problem by
defining the problem without prejudice or assumption (see Table 4.1). They
define the problem that they see, and in the scope of the measurable or tangible
thing that they want. "

*** "DEFINING THE PROBLEM AS A VARIABLE "

"Perhaps the most useful approach for defining the problem well is structuring
it as a measurable variable. With this, we view the problem as something we can
measure objectively, and we remove the guessed solution and a lot of emotion. We
know that we have a problem when this variable is not in the range we want (that
is, “out of spec”), and we don’t have a problem once it’s brought into a range
that’s acceptable (“in spec”). "

*** "KEEPING IN YOUR SCOPE "

"I’ve frequently seen teams define problems as too broad or out of their scope.
Doing so will confuse the problem-solver or team, and cause delays in one of
three ways: • They consider and study a range of variables that is too wide •
They work on problems that are outside of their power, skills, or authority •
They’re actually running away from the problem in some way "

*** "AVOIDING ASSUMPTIONS "

"One of the most dangerous—and most pervasive—mistakes when creating a problem
definition is letting some assumption about the key drivers sneak in before
really understanding the full scope of the problem. "

"Always check that you are operating at the right level and get the facts to
confirm that, even when you are not invited to do so! "

*** "NOW: KNOW WHAT PROBLEM YOU’RE SOLVING "

"It’s time to go back to the problem you’re working on and make sure you really
know what it is. Clear your mind of prejudices and assumptions, and look to
define the problem as something you can objectively measure to determine whether
the problem is happening or not. Ask yourself these questions when considering
your problem definition: "

"• Is it defined as a measurable variable? • Does it clearly translate to your
higher-level goals? • Is it within your sphere of influence, or are you
overreach- ing and need help? • Does your definition include any assumptions
about what is causing the problem?"

** "Dig Into the Fundamentals"
*** intro   
"When a system isn’t working right, someone has to understand how it’s meant to
work, at the right depth, in order to fix it. Your job as a problem-solver is to
dig deep enough into the fundamen- tals of the specific parts of the system that
affect the problem so you can solve it in a methodical, step-by-step way. This
is true for machines, mortgage processing systems, and our brains. So whether
it’s your toilet, your inventory system, or your achy left shoulder,
understanding the fundamentals behind it is going to help you. For solving hard
problems, it’s a critical factor to success. "

*** "UNDERSTANDING WHAT CONTROLS THE PRIMARY VARIABLE "

"For a hard problem in a complex system, you’re going to get quickly overwhelmed
if you try to dig into everything at once. "

"A great problem-solver won’t attempt to learn everything: To do so will waste
tremendous time without making progress. "

" Instead, they’ll dig into what’s relevant. The relevant parts of the system
are those that impact the primary variable "

" You want to understand the fundamentals of the small portion of the system
that directly controls your primary variable, rather than trying to understand
the whole thing. "

"Second, sometimes you can’t see what’s going on. I call this the “it’s dark
down there” problem. When my team was helping with an unproductive oil well
hundreds of feet below the surface, there was precious little data about the
conditions in the well. They solved the problem by mastering the well map and
studying the geological science. "

"Third, sometimes the problem is unique or only happened once."

*** "WHY PATTERN OF FAILURE ALONE IS INSUFFICIENT "

"Finally, the variable you need to fix may not change, so it doesn’t create a
pattern. "

"you can sometimes solve prob- lems by finding the pattern of failure. This can
be a valid approach to start with, but with hard problems it is unlikely to
resolve the issue. "

"First, correlation is not causation."

*** "NOW: DIG INTO THE FUNDAMENTALS "

"Time to practice digging into the fundamentals! If you have a cur- rent
problem, go figure out how the system works: make direct observations, flick
through the manual, do research online. Just make sure you’re understanding the
highest-level variables, rather than learning everything about it. "

** "Don’t Rely on Experts "
*** "NOW: DON’T RELY ON EXPERTS 
Before you engage your next expert, decide what questions you want to ask them.
Each of these questions should: 1. Be related to smelling the problem or digging
into the fundamentals. 2. Not be asking for an opinion or solution, but instead
for simple facts. Set expectations with the expert up-front that you aren’t
asking them to solve the problem, but that you’ll be frequently asking for
clarifications of unclear terms that they use. "

** "Believe in a Simple Solution"
*** intro
    "If you don’t believe in a simple solution, you are very unlikely to find it,
whether it is there or not. And usually, it’s there. So if you want to become a
great problem-solver, you need to develop the belief, and therefore adopt the
behaviors, that there is a simple solution. The only way to do this is to go
find evidence for yourself. "

*** "NOW: BELIEVE IN A SIMPLE SOLUTION Remind
    yourself of a situation where you solved a problem and it was a lot simpler than
you had thought it would be. Perhaps you had an issue with someone and thought
they were going to “explode” when you raised it with them. It actually turned
out okay. Keep that story in mind as you search for other simple solu- tions to
the problems you’re tackling."

** "Make Fact-Based Decisions "
*** "GOOD AND BAD FACT-FINDING "

"Digging up information that yields insight and decision is the backbone of any
problem-solving effort: You’re there to learn the necessary facts to understand
what to change or fix. The right efforts to find facts will yield tangible steps
down the path towards the root cause; poor fact-finding will confuse you and
lead you astray."

*** "DIGGING INTO THE DATA "

"you’ll need to verify that the information you’re gather- ing is actually
representative of reality. Particularly in data-rich environments, great
problem-solvers will challenge whether sen- sor streams, studies, and so on are
providing facts. Often prob- lem-solvers face “data” that has been highly
processed and may no longer represent the relevant reality on the ground. "

*** "CHECKING FOR RELEVANCE "

"The facts you seek should also be highly relevant to your problem. "

"So what is a relevant fact? It’s a fact that’s going to answer the question
you’re asking that takes you to the next step in your problem-solving process.
When you’ve reached a certain variable, you need to get the facts to accurately
understand its behavior, and what controls it. Don’t get distracted running
about trying to measure everything you see. "

*** "AVOIDING CONFIRMATION BIAS "

"The last major risk to getting good facts is our own prejudices. While we may
not always test a solution based on our opinions or assumptions about what’s
causing the problem, confirmation bias can plague any problem-solving effort."

*** "NOW: MAKE FACT-BASED DECISIONS 
Pick a hard problem you face, or may actually be working on. Write down the
relevant facts you know and also write a list of opinions that you see floating
around—perhaps in your own mind. Now challenge your “facts” and see if some of
them are really just your opinion or the result of confirmation bias. If you are
brave enough, try this with a political issue and share it with some other
people so they can help you review it."

** "Stay on Target "
*** "THE PROBLEMS OF EXPANSIVENESS "
"What great problem-solvers do is find the root cause in a methodical way, using
what they learn along this path to eliminate vast swaths of possible root causes
and avenues of inquiry without actually hav- ing to study them directly. I"

"expansive thinking is wonderful when you’re creating new things. But when
you’re solving a practical problem, it’s completely unhelpful. Great
problem-solvers instead reduce and eliminate possibilities in order to stay on
target. They are masters of simplifying. "

*** "STAYING ON TARGET "
"our job is to efficiently find the root cause. So instead of expanding each
variable, we want to see if we can eliminate some of the “high level” variables
right at the start. Each one we get rid of has many subvariables that sit below
it and we can then ignore. "

"By elim- inating the variables closest to the primary variable, we imme-
diately eliminate many potential root causes, and we can avoid collecting data
about or looking deeply into most of the process or system. "

*** "THETHE POWER OF SIMPLIFYING "

"This iterative behavior of digging in, and then simplifying, is the on-target
path to root cause. You’ll know that you’ve found the root cause when you
identify, understand, and measure the off-spec variable that is directly in your
control to change"

*** "NOW: STAY ON TARGET "

"Things in life are always distracting you from the task at hand. Pay attention
to this in the next day or so. Look for situations when someone is having a
conversation about a topic, and people get distracted and end up talking about
something completely different. Notice how you’re taking care of one task and
then find something else that needs fixing—such as loading the dishwasher and
you notice the floor needs to be swept, and then moments later you’re
rearranging the closet. Noticing and eliminating dis- tractions will enable you
to stay on target when you’re facing down your next complex problem. "

** "How to Choose Your Method "
*** "CRITERIA FOR PICKING YOUR METHOD "

"Here is some guidance on what to look out for if you want to be able to solve
hard problems. "

"First and foremost, make sure the method you’re choosing does not encourage
guessing during its root cause analysis phase."

"Second, look for a method that starts by focusing on the problem. This will
guide you to spend time getting close to the actual problem, understand what’s
really going on, and establish a pattern of failure."

"In the end, ask yourself whether the problem-solving method you’re looking at
is designed to encourage you to effectively use all of the problem-solving
behaviors that you’ve learned. "

*** "VARIABLE ANALYSIS "
1. *Define the problem.*
 - What problem are you trying to solve?
 - Determine the primary variable
  - Closely inspect the point of failure or failed output
  - What measurable property do you want to change?
  - Is it possible to define the problem using a more specific variable?

2. *Describe the problem: describe the problem in detail.*
 - What does the problem look like? 
 - When did the problem start? 
 - How often does the problem occur? 
 - Where does the problem first occur? 
 - When where don’t you see the problem? "
   
3. *Create a variable tree: develop each layer of sub-variables by understanding how the process works*
 - How is the process designed to control the primary variable?
 - What else determines the value of the primary variable?
 - Can we combine any of the sub-variables?
  
4. *Eliminate sub-variables from the tree*
 - What should the value of each sub-variable be to prevent the problem from occurring? 
   - What is the relationship between each sub-variable and the primary variable?

 - Eliminate sub-variables that do not contribute to the problem 
   - What is the actual value of the sub-variable during failure? During non-failure? 
   - What tests could you use to eliminate variables that are difficult to measure? 
   - What does the pattern of failure tell you? 

 - Expand sub-variables that have not been eliminated (iterating step 3)

 - Start with sub-variables that the pattern-of-failure suggests are most likely to contribute to the problem"

 - Continue to expand and eliminate sub-variables until you have found the out-of-spec variable(s) that are directly in your control 
   - Can you explain exactly how the out-of-spec sub-variable(s) contribute(s) directly to the problem? 

 - If you get stuck. . . 
   - Have you eliminated a sub-variable that you should not have?
   - Have you missed a sub-variable?
     
5. *Implement the solution*
 - Implement the solution 
 - Verify the solution "

"the process works a. How is the process designed to control the primary
variable? b. What else determines the value of the primary variable? c. Can we
combine any of the sub-variables?"

*** "NOW: CHOOSE YOUR METHOD "

"If you have a method that you currently use, decide now whether it’s robust
enough to help you solve hard problems. If it is, won- derful! Keep going and
practice those behaviors. If the method you use isn’t strong enough, or you
don’t have a method at all, do a bit of research to find a method you like.
Perhaps ask around with your friends to see what they find useful, and evaluate
that."

"Go Solve Some Problems "
  
* useful resources
** good reads
 https://www.amazon.com/Best-Sellers-Books-Decision-Making-Problem-Solving/zgbs/books/2679

 https://www.linkedin.com/pulse/10-must-read-books-creative-thinking-innovation-ren%C3%A9-de-ruijter

 https://www.quora.com/Can-anyone-name-some-good-books-for-problem-solving

 https://www.ideaconnection.com/books/
